---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.20.4
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/apps/external-secrets/values.yaml
    - repoURL: git@github.com:Ahmedevelop/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:Ahmedevelop/homelab.git
      targetRevision: main
      path: apps/external-secrets        # <— where your two YAMLs live
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
