---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  annotations:
    argocd.argoproj.io/sync-wave: "4" #store after SDK server & certs are in place
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token   # secret with token
            namespace: external-secrets
            key: token                     # ref to key 
      # locally available SDK server
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caBundle: |-
        -----BEGIN CERTIFICATE-----
        MIIDBTCCAe2gAwIBAgIRAI6HwMDf6ZSuEB3O31zBDE8wDQYJKoZIhvcNAQELBQAw
        HDEaMBgGA1UEAxMRYml0d2FyZGVuLXJvb3QtY2EwHhcNMjUxMDI3MTUxMjExWhcN
        MzUxMDI1MTUxMjExWjAcMRowGAYDVQQDExFiaXR3YXJkZW4tcm9vdC1jYTCCASIw
        DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOEkKZGekzLTIwLEkh1RhjZATtta
        PCkzFcfZWTnPcH6wiAH8MKqsAEx0ujojqfce/Pdk7CDl3qjBobZLepE8w34uZOKK
        HaJJ/yuULGdZIWX7w8ljoC67q7twQgsblgEj/0X5+6yM8leunykuJkyP+p/l9D4R
        vIL1xhd/u1MWsiWfeHo37cy55l+Uh96F1FecnEeREQv/rcLpNcdwDh4B3JVGl22K
        796eK7PMB8lJ5RBRnMGuc9zjqare626xP1ce5DwqrqoiHYF2ZdSbZxYjcy3TmVrS
        vdbSs86gX/orbs1SitLsvSySgr7Ni/69exNPtTGTJ8ru0jqE2lOwNfp3CgkCAwEA
        AaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE
        FP+ahiDYIKoc+tNwrsmuXKXW7ZOtMA0GCSqGSIb3DQEBCwUAA4IBAQCKqZ7tXqgC
        Yo5GaOvwhPYxUVbp486h/Uxp6J+cwF84kMncmWcBrymZ6Ey2UsTflu+WacmlKNuj
        Ot/0yrx3EBPiU4JCFcfwQnvLS34E/xqUSdW7Rt5D16CltIlsMGiBbBMSBWynWGu4
        CLkq7Jri1jLIHU8JtKaru3cXLt7wHf9qvAB3sj7IOimjGIycO2cOCkhXvO8Ilggx
        rWs7TBtJyxpbm5OnFSujN042/WSu2IwmACVTHbAtfFboG8jAFaiNuXMRZCNW20iv
        qEHU2+WKF30J+lYRGfaXlJxdVBQU8jIF8Iu136C1C5sXUN/nR0rOivku0fXW7IOo
        xPBgkQh+cfL4
        -----END CERTIFICATE-----
      organizationID: "0d7978f1-88a1-457b-bf71-b38100a70e54"
      projectID: "28bc9454-96ca-4afc-ba5b-b38300cb2dd7"
