apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.9.1            
      helm:
        parameters:
          - name: installCRDs
            value: "true"
        valueFiles:
          - $values/apps/cert-manager/values.yaml
    - repoURL: git@github.com:Ahmedevelop/homelab.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:Ahmedevelop/homelab.git
      targetRevision: main
      path: apps/cert-manager
      directory:
        recurse: true
        include: '{issuers/*.yaml,prod/*.yaml,staging/*.yaml,cloudflare-token.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true