apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    creationPolicy: Owner               
    template:
      type: Opaque
  data:
    - secretKey: grafana-user
      remoteRef:
        key: 84a5344f-1680-4bf4-b140-b3870070ef53
    - secretKey: grafana-password
      remoteRef:
        key: e751d175-2970-481c-be17-b3870071b6b0