---
globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

providers:
  kubernetesIngress:
    ingressClass: traefik-external
  kubernetesCRD:
    namespaces:
      - traefik-external

ingressClass:
  enabled: true
  isDefaultClass: false

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.8.41

ports:
  web:
    expose:
      default: true
    exposedPort: 80
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true

logs:
  general:
    level: DEBUG
